name: Build

on:
  issue_comment:
    types: [created]

jobs:
  apk:
    runs-on: ubuntu-latest
    if: github.actor == 'robertsLando' && github.event.issue.url == 'https://api.github.com/repos/robertsLando/pkg-binaries/issues/5'
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1

      - name: "Install deps"
        run: sudo apt-get install rename

      - name: "Build ${{ github.event.comment.body }}"
        run: |
          chmod +x build.sh
          ./build.sh ${{ github.event.comment.body }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "${{ github.event.comment.body }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      