name: Build

on:
  issue_comment:
    types: [created]

jobs:
  apk:
    runs-on: self-hosted
    timeout-minutes: 3000
    if: github.actor == 'robertsLando' && github.event.issue.url == 'https://api.github.com/repos/robertsLando/pkg-binaries/issues/5'
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1

      # - name: "Install deps"
      #   run: sudo apt-get install rename

      - name: "Build ${{ github.event.comment.body }}"
        timeout-minutes: 3000
        id: build
        run: |
          echo "::set-output name=FETCHED::${ls | grep build}"
      - name: "Check output ${{ steps.build.outputs.FETCHED }}"
        run: |
          echo DONE
      # - name: Upload to release
      #   uses: svenstaro/upload-release-action@v1-release
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./${{ steps.build.outputs.FETCHED }}
      #     asset_name: ${{ steps.build.outputs.FETCHED }}
      #     tag: v1.0.0
      #     overwrite: true
      